# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

    http_client:
        scoped_clients:
            fixer.client:
                base_uri: '%env(FIXER_IO_BASE_URL)%'
            google.client:
                base_uri: 'https://www.google.com/search' # https://www.google.com/search?q=1+usd+to+eur
                headers:
                    DNT: '1'
                    User-Agent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:101.0) Gecko/20100101 Firefox/101.0'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
