version: '3.8'
services:
  nginx:
    image: nginx:1.23-alpine
    volumes:
      - ./public/:/var/www/html/public/:ro
      - ./docker/nginx/http.d/:/etc/nginx/conf.d/
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '8080:80'
    links:
      - php

  php:
    environment:
      TZ: Europe/Amsterdam
    build:
      context: ./docker/php/
    volumes:
      - ./:/var/www/html/
      #- ./docker/php/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:ro
